version: '3.7'

services:
  database:
    image: postgres:latest
    networks:
      development:
        aliases:
          - database
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=local"
  costjanitor.host.api:
    image: cost-janitor-api
    build:
      context: .
      dockerfile: src/CostJanitor.Host.Api/Dockerfile
  costjanitor.host.eventconsumer:
    image: cost-janitor-eventconsumer
    build:
      context: .
      dockerfile: src/CostJanitor.Host.EventConsumer/Dockerfile

networks:
  development:
    name: development