version: '3.7'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=local"
  costjanitor.host.api:
    image: cost-janitor-api
    build:
      context: .
      dockerfile: src/CostJanitor.Host.Api/Dockerfile
  costjanitor.host.eventconsumer:
    image: cost-janitor-event-consumer
    build:
      context: .
      dockerfile: src/CostJanitor.Host.EventConsumer/Dockerfile