apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-janitor-api-deployment
  namespace: developerautomation-xavgy
  labels:
    project: developerautomation
    department: cloudengineering
    component: cost-janitor
    app: cost-janitor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cost-janitor-api
  template:
    metadata:
      labels:
        project: developerautomation
        department: cloudengineering
        app: cost-janitor-api
    spec:
      priorityClassName: selfservice
      containers:
      - name: cost-janitor-api
        image: 642375522597.dkr.ecr.eu-west-1.amazonaws.com/dfds.developerautomation-xavgy.cost-janitor:cost-janitor-api-$(Build.BuildId)
        ports:
        - containerPort: 54323
          name: web
        - containerPort: 8080
          name: metrics
        env:
          - name: Kafka__Configuration__sasl.username
            valueFrom:
              secretKeyRef:
                name: kafka-credentials
                key: username
          - name: Kafka__Configuration__sasl.password
            valueFrom:
              secretKeyRef:
                name: kafka-credentials
                key: password
          - name: RDS_HOST
            valueFrom:
              secretKeyRef:
                name: costjanitor-rdspostgresql-conn
                key: endpoint
          - name: RDS_PORT
            valueFrom:
              secretKeyRef:
                name: costjanitor-rdspostgresql-conn
                key: port
          - name: RDS_USERNAME
            valueFrom:
              secretKeyRef:
                name: costjanitor-rdspostgresql-conn
                key: username
          - name: RDS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: costjanitor-rdspostgresql-conn
                key: password
          - name: ConnectionStrings__ApplicationContext
            value: $(RDS_USERNAME)
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "200m"