apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-janitor-event-consumer-deployment
  namespace: developerautomation-xavgy
  labels:
    project: developerautomation
    department: cloudengineering
    component: cost-janitor
    app: cost-devops-janitor-event-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cost-janitor-event-consumer
  template:
    metadata:
      labels:
        project: developerautomation
        department: cloudengineering
        app: cost-janitor-event-consumer
    spec:
      priorityClassName: selfservice
      containers:
      - name: cost-janitor-event-consumer
        image: 642375522597.dkr.ecr.eu-west-1.amazonaws.com/dfds.developerautomation-xavgy.cost-janitor:cost-janitor-event-consumer-$(Build.BuildId)
        env:
          - name: Kafka__Configuration__sasl.username
            valueFrom:
              secretKeyRef:
                name: kafka-credentials
                key: username
          - name: Kafka__Configuration__sasl.password
            valueFrom:
              secretKeyRef:
                name: kafka-credentials
                key: password
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "200m"