apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: cost-janitor-rds
  namespace: developerautomation-xavgy
spec:
  providerConfigRef:
    name: cost-janitor-provider-config
  forProvider:
    region: eu-west-1
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "11"
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    namespace: developerautomation-xavgy
    name: costjanitor-rdspostgresql-conn