// <auto-generated />
using System;
using CostJanitor.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CostJanitor.Infrastructure.Migrations
{
    [DbContext(typeof(DomainContext))]
    [Migration("20210209140952_xaxa")]
    partial class xaxa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CostItemReportItem", b =>
                {
                    b.Property<Guid>("_costItemsId")
                        .HasColumnType("uuid");

                    b.Property<string>("_costItemsLabel")
                        .HasColumnType("text");

                    b.Property<string>("_costItemsCapabilityIdentifier")
                        .HasColumnType("text");

                    b.HasKey("_costItemsId", "_costItemsLabel", "_costItemsCapabilityIdentifier");

                    b.HasIndex("_costItemsLabel", "_costItemsCapabilityIdentifier");

                    b.ToTable("CostItemReportItem");
                });

            modelBuilder.Entity("CostJanitor.Domain.Aggregates.ReportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ReportItem");
                });

            modelBuilder.Entity("CostJanitor.Domain.ValueObjects.CostItem", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("CapabilityIdentifier")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReportItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Label", "CapabilityIdentifier");

                    b.HasIndex("ReportItemId");

                    b.ToTable("CostItem");
                });

            modelBuilder.Entity("CostItemReportItem", b =>
                {
                    b.HasOne("CostJanitor.Domain.Aggregates.ReportItem", null)
                        .WithMany()
                        .HasForeignKey("_costItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostJanitor.Domain.ValueObjects.CostItem", null)
                        .WithMany()
                        .HasForeignKey("_costItemsLabel", "_costItemsCapabilityIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CostJanitor.Domain.ValueObjects.CostItem", b =>
                {
                    b.HasOne("CostJanitor.Domain.Aggregates.ReportItem", null)
                        .WithMany("CostItems")
                        .HasForeignKey("ReportItemId");
                });

            modelBuilder.Entity("CostJanitor.Domain.Aggregates.ReportItem", b =>
                {
                    b.Navigation("CostItems");
                });
#pragma warning restore 612, 618
        }
    }
}
